"""Render stage — produce 1080 × 1920 H.264 MP4 with burned-in captions.

For each requested clip:
1. Build an ffmpeg crop=filter_complex from the crop_plan keyframes using
   sendcmd (per-frame filter param injection).
2. Overlay the .ass subtitle file generated by the captions stage.
3. Scale to 1080 × 1920, encode H.264 crf=23 preset=fast.

Output artifact ``rendered_clips``:
  [{"clip_id": str, "path": str, "start": float, "end": float}]
"""

from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path

from .context import JobContext

STAGE = "render"
OUT_W, OUT_H = 1080, 1920
logger = logging.getLogger("reframe.render")


def run(ctx: JobContext) -> None:
    ctx.progress(STAGE, 0.0, "Starting render…")

    video_path = Path(ctx.require_artifact("video_path"))
    crop_plan: list[dict] = ctx.require_artifact("crop_plan")
    clips: list[dict] = ctx.require_artifact("clip_candidates")
    ass_path = ctx.artifacts.get("ass_path")

    crop_w: int = ctx.artifacts["crop_w"]
    crop_h: int = ctx.artifacts["crop_h"]

    rendered: list[dict] = []

    for idx, clip in enumerate(clips):
        clip_id = clip["id"]
        start = clip["start"]
        end = clip["end"]
        out_path = ctx.artifact_path(f"clip_{clip_id}.mp4")

        ctx.progress(STAGE, idx / len(clips) * 95, f"Rendering clip {idx+1}/{len(clips)}…")

        # Build per-frame crop commands using sendcmd
        sendcmd_file = _write_sendcmd(crop_plan, start, end, crop_w, crop_h)

        _run_ffmpeg(
            video_path=video_path,
            out_path=out_path,
            start=start,
            end=end,
            crop_w=crop_w,
            crop_h=crop_h,
            sendcmd_file=sendcmd_file,
            ass_path=ass_path,
        )

        Path(sendcmd_file).unlink(missing_ok=True)

        rendered.append({
            "clip_id": clip_id,
            "path": str(out_path),
            "start": start,
            "end": end,
        })

    ctx.artifacts["rendered_clips"] = rendered
    ctx.progress(STAGE, 100.0, f"Rendered {len(rendered)} clip(s)")


def _write_sendcmd(
    crop_plan: list[dict],
    start: float,
    end: float,
    crop_w: int,
    crop_h: int,
) -> str:
    """Write an ffmpeg sendcmd file for per-frame crop parameter injection."""
    lines: list[str] = []
    relevant = [p for p in crop_plan if start <= p["time"] <= end]
    if not relevant:
        relevant = crop_plan[:1] if crop_plan else [{"time": start, "x": 0, "y": 0}]

    for i, kf in enumerate(relevant):
        t = round(kf["time"] - start, 4)
        x = kf["x"]
        y = kf["y"]
        if i == 0:
            lines.append(f"0 [enter] crop x {x};")
            lines.append(f"0 [enter] crop y {y};")
        else:
            lines.append(f"{t} [enter] crop x {x};")
            lines.append(f"{t} [enter] crop y {y};")

    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False)
    tmp.write("\n".join(lines))
    tmp.close()
    return tmp.name


def _run_ffmpeg(
    video_path: Path,
    out_path: Path,
    start: float,
    end: float,
    crop_w: int,
    crop_h: int,
    sendcmd_file: str,
    ass_path: str | None,
) -> None:
    duration = end - start

    filter_parts = [
        f"sendcmd=f='{sendcmd_file}'",
        f"crop={crop_w}:{crop_h}",
        f"scale={OUT_W}:{OUT_H}:flags=lanczos",
    ]
    if ass_path and Path(ass_path).exists():
        # escape colons in path for ffmpeg filter syntax
        safe_ass = ass_path.replace("\\", "/").replace(":", "\\:")
        filter_parts.append(f"ass='{safe_ass}'")

    vf = ",".join(filter_parts)

    cmd = [
        "ffmpeg", "-y",
        "-ss", str(start),
        "-i", str(video_path),
        "-t", str(duration),
        "-vf", vf,
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        "-b:a", "128k",
        "-movflags", "+faststart",
        str(out_path),
    ]

    try:
        subprocess.run(
            cmd, capture_output=True, text=True, timeout=1800, check=True
        )
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            f"FFmpeg render failed for clip: {exc.stderr[-400:]}"
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError("FFmpeg render timed out") from exc
